version: "3"
services:
  workspace:
    tty: true
    # working_dir: /root
    # entrypoint: bash
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 8080:80
    environment:
      PORT: 80
      SLACK_TOKEN: $SLACK_TOKEN
      SLACK_CHANNEL: $SLACK_CHANNEL
    # volumes:
    #   - ./go/src:/root/go/src
    #   - ./commands:/root/commands
    #   - /var/run/docker.sock:/var/run/docker.sock
